backend:
  name: git-gateway
  branch: master 

media_folder: "public/images" 
public_folder: "/images" 

collections:
  - name: "docs"
    label: "Documentación"
    folder: "src/content/docs"
    create: true
    nested:
      depth: 5 # Permite hasta 5 niveles de subcarpetas
      summary: '{{title}}'
    meta:
      path:
        widget: string
        label: "Ruta / Carpeta"
        index_file: "index"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descripción", name: "description", widget: "string", required: false}
      - {label: "Cuerpo", name: "body", widget: "markdown"}
